crop_task_node:
  ros__parameters:
    camera_topic: "/camera/image_raw"
    stop_topic: "patrol/stop"
    task_command_topic: "/main/task_simple"
    task_command_stop: 2
    task_command_resume: 1
    arm_event_topic: "crop_task/events"
    arm_done_topic: ""
    simulate_arm: true
    simulated_arm_duration: 6.0
    hsv_lower: [18.0, 110.0, 80.0]
    hsv_upper: [32.0, 255.0, 255.0]
    min_area_ratio: 0.012
    min_area_pixels: 2200.0
    detection_hold_frames: 5
    release_frames: 12
    blur_kernel_size: 5
    morph_kernel_size: 7
    morph_iterations: 2
    publish_debug_image: true
    debug_image_topic: "crop_task/debug_image"
