/**:
  controller_server:
    ros__parameters:
      use_sim_time: True
      controller_frequency: 20.0
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.5
      min_theta_velocity_threshold: 0.001
      progress_checker_plugins: ["progress_checker"]
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.2
        stateful: True
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        debug_trajectory_details: True
        min_vel_x: 0.0
        min_vel_y: 0.0
        # max_vel_x: 0.15  # Original Value
        max_vel_x: 0.22
        max_vel_y: 0.0
        # max_vel_theta: 1.0  # Original Value
        max_vel_theta: 2.5
        min_speed_xy: 0.0
        # max_speed_xy: 0.15  # Original Value
        max_speed_xy: 0.22
        min_speed_theta: 0.0
        # acc_lim_x: 1.5  # Original Value
        acc_lim_x: 2.5
        acc_lim_y: 0.0
        # acc_lim_theta: 3.2  # Original Value
        acc_lim_theta: 5.0
        # decel_lim_x: -2.0  # Original Value
        decel_lim_x: -2.5
        decel_lim_y: 0.0
        # decel_lim_theta: -3.2  # Original Value
        decel_lim_theta: -5.0
        vx_samples: 40
        vy_samples: 5
        vtheta_samples: 20
        sim_time: 1.7
        linear_granularity: 0.05
        angular_granularity: 0.025
        transform_tolerance: 0.2
        xy_goal_tolerance: 0.25
        trans_stopped_velocity: 0.25
        short_circuit_trajectory_evaluation: True
        limit_vel_cmd_in_traj: False
        stateful: True
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", ObstacleFootprintCritic]
        BaseObstacle.scale: 0.05
        PathAlign.scale: 10.0
        GoalAlign.scale: 10.0
        PathAlign.forward_point_distance: 0.1
        GoalAlign.forward_point_distance: 0.1
        PathDist.scale: 10.0
        GoalDist.scale: 10.0
        RotateToGoal.scale: 10.0
        RotateToGoal.slowing_factor: 5.0
        RotateToGoal.lookahead_time: -1.0
        ObstacleFootprintCritic.scale: 20.0
        ObstacleFootprintCritic.threshold: 0.1
        ObstacleFootprintCritic.include_dynamic_obstacles: true
        ObstacleFootprintCritic.collision_penalty: 100.0
        ObstacleFootprintCritic.footprint_cost_mode: 0
/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        global_frame: tb3_1/odom
        robot_base_frame: tb3_2/base_link
        update_frequency: 5.0
        resolution: 0.05
        width: 3
        height: 3
        obstacle_range: 2.5
        raytrace_range: 3.0
        rolling_window: true
        plugins: ["obstacle_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: true
          observation_sources: scan
          scan:
            topic: /tb3_2/scan
            max_obstacle_height: 2.0
            clearing: true
            marking: true
            data_type: "LaserScan"
/**:
  velocity_smoother:
    ros__parameters:
      smoothing_frequency: 20.0
      scale_velocities: false
      feedback: "OPEN_LOOP"
      max_velocity: [0.25, 0.0, 2.5]
      min_velocity: [-0.25, 0.0, -2.5]
      deadband_velocity: [0.0, 0.0, 0.0]
      velocity_timeout: 1.0
      # max_accel: [1.5, 0.0, 3.2]  # Original Value
      max_accel: [2.5, 0.0, 5.0]
      # max_decel: [-1.5, 0.0, -3.2]  # Original Value
      max_decel: [-2.5, 0.0, -5.0]
      odom_topic: "/tb3_2/odom"
      odom_duration: 0.1
      use_realtime_priority: false
      enable_stamped_cmd_vel: false
