waypoints:
  - name: point1
    position: {x: 0.2, y: -0.2}
    yaw_deg: 0.0
  - name: point2
    position: {x: 1.7, y: -0.2}
    yaw_deg: 0.0
  - name: point3
    position: {x: 1.7, y: -2.3}
    yaw_deg: -90.0
  - name: point4
    position: {x: 0.2, y: -2.3}
    yaw_deg: 90.0
  - name: point1_return
    position: {x: 0.2, y: -0.2}
    yaw_deg: 0.0
