turtlebot3_patrol_stop_dummy:
  ros__parameters:
    laser_topic: /tb3_2/vl53_front_range
    laser_topic_type: range
    auto_sequence_enabled: true
    auto_stop_min: 0.17
    auto_stop_max: 0.20
    arm_service_name: /robot_arm_control
    arm_command: detect
    arm_call_timeout: 60.0
    auto_pre_task_delay: 2.0
    auto_post_task_delay: 2.0
